source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'ILABReverseVideoExporterDemo' do
  pod 'ILABReverseVideoExporter', :path => "../"
  pod 'OHQBImagePicker'
  pod 'M13ProgressSuite'
end
